import me.modmuss50.mpp.ReleaseType

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.1'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        url 'https://harleyoconnor.com/maven'
    }
    flatDir {
        dir("libs")
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    // applies to all the run configs below
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all',
                '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    //implementation ':dynamictrees:neoforge-1.21.1-1.5.0-BETA08'
    implementation "curse.maven:dynamictrees-252818:7272645"
    implementation 'curse.maven:dynamictreesplus-478155:7272755'
    implementation "curse.maven:forbidden-arcanus-309858:6875895"
    implementation 'curse.maven:jade-324717:6291517'
    implementation "curse.maven:valhelsia-core-416935:6296775"

    runtimeOnly "curse.maven:emi-580555:6420931"
    runtimeOnly "curse.maven:patchouli-306770:6842247"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

def changelogFile = file("build/changelog.txt")

publishMods {
    file = jar.archiveFile
    displayName = "${mod_name.replace(' ','')}-NeoForge-${minecraft_version} ${project.version}"
    if (changelogFile.exists()) {
        changelog.set(changelogFile.getText())
    }
    type = ReleaseType.of(version_type.toUpperCase())
    modLoaders.add("neoforge")

    curseforge {
        projectId = "416698"
        projectSlug = "dynamic-trees-forbidden-arcanus"
        accessToken = curseApiKey ?: System.getenv("CURSEFORGE_API_KEY")
        minecraftVersions.add("1.21.1")
        requires("dynamictrees")
        requires("forbidden-arcanus")
    }
//    modrinth {
//        projectId = ""
//        accessToken = modrinthToken ?: System.getenv("MODRINTH_TOKEN")
//        minecraftVersions.add("1.21.1")
//        requires("vdjF5PL5") //dt
//        requires("MdlnLS7Q") //f&a
//    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
