modLoader="javafml"
loaderVersion="[36,37)"
license="MIT"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-ForbiddenAndArcanus/issues"

[[mods]]
modId="dtforbiddenarcanus"
version="${file.jarVersion}"
displayName="Dynamic Trees for Forbidden and Arcanus"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/ForbiddenAndArcanus.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-forbidden-arcanus"
logoFile=""
credits=""
authors="Max Hyper"
description='''
Compatibility Mod between Dynamic trees and Forbidden and Arcanus
'''

[[dependencies.dtforbiddenarcanus]]
    modId="forge"
    mandatory=true
    versionRange="[36,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtforbiddenarcanus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtforbiddenarcanus]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtforbiddenarcanus]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtforbiddenarcanus]]
    modId="forbidden_arcanus"
    mandatory=true
    versionRange="[16.2.0-beta-3,)"
    ordering="AFTER"
    side="BOTH"
